# Generated by Django 4.1.5 on 2023-01-08 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_product_id_order_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cat',
            new_name='product',
        ),
    ]
