# Generated by Django 4.1.4 on 2023-01-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_cat_photo_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=600)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('category', models.CharField(choices=[('F', 'Furniture'), ('T', 'Toy'), ('C', 'Cloth'), ('M', 'Mobile Phone'), ('L', 'Laptop')], default='F', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('F', 'Furniture'), ('T', 'Toy'), ('C', 'Cloth'), ('M', 'Mobile Phone'), ('L', 'Laptop')], default='F', max_length=1),
        ),
    ]
